version: '2'
services:
  web:
    build: .
    ports:
      - 8080:80
    links:
      - db
      - redis
    env_file:
      - docker/env
    volumes: 
      - ./app:/var/www/html/app
      - ./bin:/var/www/html/bin
      - ./dev:/var/www/html/dev
      - ./pub/media:/var/www/html/pub/media
      - ./composer.lock:/var/www/html/composer.lock
      - ./composer.json:/var/www/html/composer.json
      - ./magento.nginx.conf:/var/www/html/magento.nginx.conf
    networks:
      env_net:
        ipv4_address: 171.28.1.1
   
  db:
    image: mysql:5.7.19
    volumes:
       - db-data:/var/lib/mysql
       - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
       - 3306:3306 
    env_file:
      - docker/env
    networks:
      env_net:
        ipv4_address: 171.28.1.2
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    networks:
      env_net:
        ipv4_address: 171.28.1.3
      
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      env_net:
        ipv4_address: 171.28.1.4
    
volumes:
  db-data:
      
networks:
  env_net:
    ipam:
      driver: default
      config:
        - subnet: 171.28.0.0/16
